# - name: Ec2-user and Route 53 connection
#   hosts: localserver
#   connection: local
#   vars:
#     ami_id: ami-0220d79f3f480ecf5
#     sg_id: sg-04eb2974139741695 
#     zone_id: "Z100354714Q7Y7MA4LCQB" 
#     domain_name: "anjana.fun"
#     instances: 
#     - mongodb
#   tasks: 
#   - name: create ec2 instance
#     amazon.aws.ec2_instance:
#       name: "{{ item }}" # to refer loop keyword we use item.
#       instance_type: t3.micro
#       security_group: "{{ sg_id }}"
#       image_id: "{{ ami_id }}"
#       tags:
#         Name: "{{ item }}"
#   loop: "{{ instances }}"
#   register: ec2_output # to store the output we use register

# to print the output
# - name: print the ec2_output
#   ansible.builtin.debug:
#     msg: "{{ ec2_output }}"

- name: create ec2 and r53
  hosts: localserver
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-04eb2974139741695 # replace with your SG ID
    zone_id: "Z100354714Q7Y7MA4LCQB" # replace with your ID
    domain_name: "anjana.fun"
    # we can pass instances through command line using -e
    instances: 
     - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"
  