[frontend]
13.220.179.15

[localServer]
localhost

[localServer:vars] #inventory variables defined via groupname:vars here two groups rontend n local server
NAME=from inventory
FAVCOLOUR=Peach
NAME= Anjana
CITY= Delhi