[frontend]
100.53.219.106

[localServer]
localhost

[localServer:vars] #inventory variables defined via groupname:vars here two groups rontend n local server
NAME=from inventory
FAVCOLOUR=Peach
NAME= Anjana
CITY= Delhi